# Generated by Django 5.0.6 on 2024-07-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
